Fiap.Aula04/Fiap.Aula04.Web/Models/Carro.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Fiap.Aula04.Web.Models
{
    public class Carro
    {
        [HiddenInput]
        public int IdCarro { get; set; }
        public String? Modelo { get; set; }
        public int Ano { get; set; }
        public Decimal Valor { get; set; }
        public String? Tipo { get; set; }
        public String? Marca { get; set; }
        [Display(Name = "Possui teto solar?")]
        public Boolean TetoSolar { get; set; }
        [Display(Name = "Combustível")]
        public Combustivel? Combustivel { get; set; }
    }

    public enum Combustivel
    {
        Etanol, Gasolina, Flex, Eletrico, Diesel
    }
}

Fiap.Aula04/Fiap.Aula04.Web/Models/Cliente.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Fiap.Aula04.Web.Models
{
    public class Cliente
    {
        [HiddenInput]
        public int Codigo { get; set; }
        [Display(Name = "Nome Completo")]
        public String? NomeCompleto { get; set; }
        [Display(Name = "Data de Nascimento")]
        public DateTime DataNascimento { get; set; }
        [Display(Name = "Cliente Fidelizado?")]
        public Boolean Fidelizado { get; set; }
        [Display(Name = "Gênero")]
        public Genero Genero { get; set; }
        [Display(Name = "Formação")]
        public String? Formacao { get; set; }
    }

    public enum Genero
    {
        Feminino, Masculino, Outros
    }
}

Fiap.Aula04/Fiap.Aula04.Web/Models/ErrorViewModel.cs
namespace Fiap.Aula04.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Fiap.Aula04/Fiap.Aula04.Web/Controllers/CarroController.cs
using Fiap.Aula04.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Fiap.Aula04.Web.Controllers
{
    public class CarroController : Controller
    {
        private static List<Carro> _lista = new List<Carro>();
        private static int _id = 0;

        public IActionResult Index()
        {
            //TempData["lista"] = _lista;
            return View(_lista);
        }

        [HttpGet]
        public IActionResult Cadastrar()
        {
            //mockup de um recebimento de dados de uma requisição para o select
            CarregaMarcas();
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(Carro carro)
        {
            carro.IdCarro = ++_id;
            _lista.Add(carro);
            TempData["msg"] = "Carro Cadastrado!";
            //redireciona para o get de cadastrar, zerando os campos
            return RedirectToAction("Cadastrar");
        }

        private void CarregaMarcas()
        {
            var lista = new List<String>(new String[] { "Fiat", "Volkswagen", "Ford", "Chevrolet" });
            ViewBag.marcas = new SelectList(lista);
        }

        [HttpGet]
        public IActionResult Editar(int id)
        {
            CarregaMarcas();
            //Recuperar a posicao do carro na lista
            var index = _lista.FindIndex(c => c.IdCarro == id);
            //recuperar o carro atraves do id;
            var carro = _lista[index];
            //enviar o carro pra view
            return View(carro);
        }

        [HttpPost]
        public IActionResult Editar(Carro carro)
        {
            //Recuperar a posicao do carro na lista
            var index = _lista.FindIndex(c => c.IdCarro == carro.IdCarro);
            //recuperar o carro atraves do id;
            _lista[index] = carro;            
            TempData["msg"] = "Carro Editado!";
            //enviar o carro pra view
            return RedirectToAction("Editar");
        }

        [HttpPost]
        public IActionResult Remover(int id)
        {
            //busca o carro na lista atraves de seu id, pra pegar o index.
            _lista.RemoveAt(_lista.FindIndex(c => c.IdCarro == id));
            TempData["msg"] = "Carro Excluido!";
            return RedirectToAction("Index");
        }




    }
}

Fiap.Aula04/Fiap.Aula04.Web/Controllers/ClienteController.cs
using Fiap.Aula04.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Fiap.Aula04.Web.Controllers
{
    public class ClienteController : Controller
    {
        private static List<Cliente> _listaCliente = new();
        private static int _id = 0;
        private static int _index;

        public void CarregaFormacao()
        {
            var lista = new List<String>(new String[] { "Fundamental", "Medio", "Superior" });
            ViewBag.formacoes = new SelectList(lista);
        }

        public IActionResult Index()
        {
            return View(_listaCliente);
        }



        public IActionResult Cadastrar()
        {
            CarregaFormacao();
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(Cliente cliente)
        {
            cliente.Codigo = ++_id;
            _listaCliente.Add(cliente);
            TempData["msg"] = "Cliente Cadastrado!";
            return RedirectToAction("Cadastrar");

        }

        [HttpGet]
        public IActionResult Editar(int id)
        {
            CarregaFormacao();
            _index = _listaCliente.FindIndex(c => c.Codigo == id);
            var cliente = _listaCliente[_index];
            return View(cliente);
        }

        [HttpPost]
        public IActionResult Editar(Cliente cliente)
        {
            _index = _listaCliente.FindIndex(c => c.Codigo == cliente.Codigo);
            _listaCliente[_index] = cliente;
            TempData["msg"] = "Cliente editado";
            return RedirectToAction("Editar");
        }

        [HttpPost]
        public IActionResult Remover(int id)
        {
            _listaCliente.RemoveAt(_listaCliente.FindIndex(c => c.Codigo == id));
            TempData["msg"] = "Cliente Excluido";
            return RedirectToAction("Index");
        }


    }
}

Fiap.Aula04/Fiap.Aula04.Web/Controllers/HomeController.cs
using Fiap.Aula04.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Fiap.Aula04.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Fiap.Aula04/Fiap.Aula04.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Aula MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Fiap.Aula04.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Aula MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Carros
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item" asp-controller="Carro" asp-action="Cadastrar">Cadastrar</a>
                                </li>
                                <li><a class="dropdown-item" asp-controller="Carro" asp-action="Index">Listar</a></li>
                                <li><hr class="dropdown-divider"></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Clientes
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item" asp-controller="Cliente" asp-action="Cadastrar">Cadastrar</a>
                                </li>
                                <li><a class="dropdown-item" asp-controller="Cliente" asp-action="Index">Listar</a></li>
                                <li><hr class="dropdown-divider"></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div>
            @RenderSection("Banner", false)
        </div>
        <div class="container">
            &copy; 2022 - Fiap.Aula04.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>