Fiap.Aula03/Fiap.Aula03.Web/Models/Calculadora.cs
namespace Fiap.Aula03.Web.Models
{
    public class Calculadora
    {
        public int Valor1 { get; set; }
        public int Valor2 { get; set; }
        public string? Operacao { get; set; }

        public int Resultado { get; set; }
    }
}

Fiap.Aula03/Fiap.Aula03.Web/Models/ErrorViewModel.cs
namespace Fiap.Aula03.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Fiap.Aula03/Fiap.Aula03.Web/Models/Produto.cs
namespace Fiap.Aula03.Web.Models
{
    public class Produto
    {
        public string? Descricao { get; set; }
        public decimal Valor { get; set; }
    }
}

Fiap.Aula03/Fiap.Aula03.Web/Models/Usuario.cs
namespace Fiap.Aula03.Web.Models
{
    public class Usuario
    {
        public String? Nome { get; set; }

        public DateOnly DtNascimento { get; set; }
        public String? Email { get; set; }
    }
}

Fiap.Aula03/Fiap.Aula03.Web/Controllers/CalculadoraController.cs
using Fiap.Aula03.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace Fiap.Aula03.Web.Controllers
{
    public class CalculadoraController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {

            return View();
        }

        [HttpPost]
        public IActionResult Index(Calculadora calc)
        {
            switch (calc.Operacao)
            {
                case "+":
                    calc.Resultado = calc.Valor1 + calc.Valor2;
                    break;
                case "-":
                    calc.Resultado = calc.Valor1 - calc.Valor2;
                    break;
                case "*":
                    calc.Resultado = calc.Valor1 * calc.Valor2;
                    break;
                case "/":
                    try
                    {
                        calc.Resultado = calc.Valor1 / calc.Valor2;
                    }
                    catch (Exception)
                    {
                        calc.Resultado = 0;
                    }
                    
                    break;
                default:
                    calc.Resultado = 0;
                    break;
            }
            //ViewBag.Resultado = calc.Resultado; - so funciona com forward (encaminhamento)
            TempData["resultado"] = calc.Resultado;
            return RedirectToAction("Index");
        }
    }
}

Fiap.Aula03/Fiap.Aula03.Web/Controllers/FuncionarioController.cs
using Microsoft.AspNetCore.Mvc;

namespace Fiap.Aula03.Web.Controllers
{
    public class FuncionarioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        
    }
}

Fiap.Aula03/Fiap.Aula03.Web/Controllers/HomeController.cs
using Fiap.Aula03.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Fiap.Aula03.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Fiap.Aula03/Fiap.Aula03.Web/Controllers/ProdutoController.cs
using Fiap.Aula03.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace Fiap.Aula03.Web.Controllers
{
    public class ProdutoController : Controller
    {
        public IActionResult Index()
        {
            ViewData["chave"] = "Cadastro de Produto";
            ViewBag.subtitulo = "Aqui é uma viewbag de produtos";
            return View();
        }

        [HttpGet] //retorna a pagina com o form
        public IActionResult Cadastrar()
        {

            return View();
        }
        [HttpPost] //recebe os parametros do form
        public IActionResult Cadastrar(Produto produto)
        {
            /*
            //Enviar a descrição do produto para a view
            ViewData["desc"] = $"Descrição: {produto.Descricao}";
            ViewBag.valor = produto.Valor;
            return Content($"Descrição: {produto.Descricao}\n Valor: R$ {produto.Valor}");
            */
            //ViewBag.prod = produto; retorno para forward

            return View("Sucesso", produto);
        }

        public IActionResult Estoque()
        {
            return View();
        }
    }
}

Fiap.Aula03/Fiap.Aula03.Web/Controllers/UsuarioController.cs
using Fiap.Aula03.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace Fiap.Aula03.Web.Controllers
{
    public class UsuarioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Cadastra()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastra(Usuario usuario)
        {
            if (usuario.Nome != null)
            {
                TempData["mensagem"] = "Cadastrado com Sucesso!";
                return View("Sucesso", usuario);
            }
            else
            {
                return View();
            }
           
            
        }
    }
}

Fiap.Aula03/Fiap.Aula03.Web/Views/Calculadora/Index.cshtml
@{
	ViewData["Title"] = "Index";
}
<form method="post" action="/calculadora/index">
	<div class="mb-3">
		<label class="form-label">Valor 1:</label>
		<input type="text" name="valor1" class="form-control" />
	</div>
	<div class="mb-3">
		<label class="form-label">Valor 2:</label>
		<input type="text" name="valor2" class="form-control" />
	</div>

	<div class="mb-3">
		<label class="form-label">Operação:</label>
		<select class="form-select" aria-label="Default select example" name="operacao">
			<option selected>Selecione a Operação</option>
			<option name="+">+</option>
			<option name="-">-</option>
			<option name="*">*</option>
			<option name="/">/</option>
		</select>
	</div>

	<input type="submit" value="Calcular" class="btn btn-primary" />
	<div class="mb-3">

@*		<h3>Resultado: @ViewBag.Resultado</h3>*@
		<h3>Resultado: @TempData["resultado"]</h3>
	</div>
</form>

Fiap.Aula03/Fiap.Aula03.Web/Views/Funcionario/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

Fiap.Aula03/Fiap.Aula03.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Fiap.Aula03/Fiap.Aula03.Web/Views/Produto/Cadastrar.cshtml
@{
    ViewData["Title"] = "Cadastrar";
}


<h1>Cadastrar</h1>

<!-- Descrição, Valor e botão -->

<form method="post" action="/produto/cadastrar">
    <div class="mb-3">
        <label class="form-label">Descrição</label>
        <input type="text" name="descricao" class="form-control" />
    </div>
    <div class="mb-3">
        <label class="form-label">Valor</label>
        <input type="text" name="valor" class="form-control"/>
    </div>
    <input type="submit" value="Cadastrar" class="btn btn-primary" />
</form>

Fiap.Aula03/Fiap.Aula03.Web/Views/Produto/Estoque.cshtml
<h1> Estoque </h1>

Fiap.Aula03/Fiap.Aula03.Web/Views/Produto/Index.cshtml
<h1> Index de Produto </h1>

Fiap.Aula03/Fiap.Aula03.Web/Views/Produto/Sucesso.cshtml
@*Recebe o objeto produto da controller*@
@model Produto

<h2>@ViewData["desc"]</h2>

<h3>
    Produtos
</h3>

@*<h4>Descrição: @ViewBag.prod.Descricao</h4>

<h4>Valor: R$ @ViewBag.prod.Valor</h4>*@

<h4>Descrição: @Model.Descricao</h4>

<h4>Valor: R$ @Model.Valor </h4>

Fiap.Aula03/Fiap.Aula03.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Fiap.Aula03.Web</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/Fiap.Aula03.Web.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Fiap.Aula03.Web</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Cadastrar">Produto</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Calculadora" asp-action="Index">Calculadora</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2022 - Fiap.Aula03.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Fiap.Aula03/Fiap.Aula03.Web/Views/Usuario/Cadastra.cshtml
@{
    ViewData["Title"] = "Cadastra";
}

<h1>Cadastro de Usuarios</h1>
<div id="msgSucesso"></div>
<form method="post" action="/usuario/cadastra"> 
    <div class="row">
        <div class="col">
                <label class="form-label">Nome</label>
                <input type="text" class="form-control" name="nome" placeholder="Nome Completo"/>
            </div>
            <div class="col">
                <label class="form-label">Data de Nascimento</label>
                <input type="date" class="form-control" name="dtAniversario" placeholder="Data de Nascimento (dd/mm/aaaa)" />
            </div>
    </div>
   
    <div class="mb-3">
        <label class="form-label">E-mail"</label>
        <input type="email" class="form-control" name="email" placeholder="email@email.com"/>
    </div>

    <input type="submit" value="ENVIAR" class="btn btn-primary"/>
</form>

Fiap.Aula03/Fiap.Aula03.Web/Views/Usuario/Sucesso.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@{
    ViewData["Title"] = "Cadastro";
}

@model Usuario;
<div class="alert alert-success" role="alert">@TempData["mensagem"]</div>

<h2>Cadastro de Usuario</h2>

<h4>Nome: @Model.Nome</h4>
<h4>Data de Nascimento: @Model.DtNascimento </h4>
<h4>Email: @Model.Email</h4>